#! /bin/zsh

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# zsh configs
if [ -f ~/.zshrc ]
then
  local zshrc_local="$HOME/.zshrc.local"
  if [ -z "$(cat $HOME/.zshrc | grep "source $zshrc_local")" ]
  then
    echo "source $zshrc_local" >> "$HOME/.zshrc"
  fi
  ln -sf "$CURRENT_DIR/zsh/.zshrc" "$zshrc_local"
else
  ln -sf "$CURRENT_DIR/zsh/.zshrc" "$HOME/.zshrc"
fi
source "$HOME/.zshrc"

# tmux configs
ln -sf "$CURRENT_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
tmux source "$HOME/.tmux.conf"

# git configs
if [ -f "$HOME/.gitconfig" ] && [ ! -L "$HOME/.gitconfig" ]
then
  mv "$HOME/.gitconfig" "$HOME/.gitconfig.local"
fi
ln -sf "$CURRENT_DIR/git/.gitconfig" "$HOME/.gitconfig"

# nvim configs
if [ -f ~/.config/nvim ]
then
	rm ~/.config/nvim
fi
ln -sfn "$CURRENT_DIR/nvim" "$HOME/.config/nvim"
